services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meeting-room-booking-sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql-server-data: